#application conf
spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
    session:
        store-type: none
    output:
        ansi:
            enabled: always

#logger
logging:
    level:
        hu:
            vaadin:
                spring: DEBUG
        org:
            springframework:
                web: INFO
#    file: path to log file

#vaadin4spring conf
vaadin4spring:
    i18n:
        message-format-cache:
            enabled: false
        message-provider-cache:
            cleanup-interval-seconds: 5

#facebook conf
facebook:
  client:
    clientId: 
    clientSecret: 
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    #https://developers.facebook.com/docs/facebook-login/permissions
    scope: email, public_profile
  resource:
    userInfoUri: https://graph.facebook.com/me